# site settings
title: Thomas Dzierzak
subtitle: Student, Engineer, Innovator
email: dzierzakt@gmail.com
description: I am a 4th year Mechanical Engineering student and am also pursuing my MBA. I love making, creating, and learning new things.
baseurl: "" # the subpath of your site, e.g. /blog
url: tommydzierzak.github.io # the base hostname & protocol for your site
author: Thomas Dzierzak
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

# social settings
#500px_url:
#facebook_url:
github_url: https://github.com/tommydzierzak
#gitlab_url:
#googleplus_url:
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/thomasdzierzak
#pinterest_url:
#slack_url:
#twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
